defmodule XamtWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :xamt

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_xamt_key",
    signing_salt: "SshzUNs1",
    same_site: "Lax",
    secure: Application.compile_env(:xamt, :secure_cookies, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # Serve the worker ourselves so we can set Service-Worker-Allowed and
  # disable caching. Plug.Static would overwrite Cache-Control and, with the
  # file living under /pwa/, browsers would otherwise limit the SW scope.
  plug :serve_service_worker

  plug Plug.Static,
    at: "/",
    from: :xamt,
    gzip: not code_reloading?,
    only: XamtWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :xamt
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug XamtWeb.Router

  defp serve_service_worker(%Plug.Conn{path_info: ["pwa", "service-worker.js"]} = conn, _opts) do
    path = Path.join(:code.priv_dir(:xamt), "static/pwa/service-worker.js")

    conn
    |> Plug.Conn.put_resp_header("service-worker-allowed", "/")
    |> Plug.Conn.put_resp_header("cache-control", "no-cache")
    |> Plug.Conn.put_resp_content_type("text/javascript")
    |> Plug.Conn.send_file(200, path)
    |> Plug.Conn.halt()
  end

  defp serve_service_worker(conn, _opts), do: conn
end
